server:
  port: 8082

spring:
  application:
    name: hljy-match
  profiles:
    active: local
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.120:8848   # Nacos 服务注册中心地址
        namespace: public                   # 如果有自定义 namespace，请改成对应的 ID
        register-enabled: true              # 启用服务注册
      config:
        import-check:
          enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${hl.db.host}:3306/db_match?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: ${hl.db.pw}
  redis:
    host: localhost
    port: 6379
    password: 
    database: 1
    timeout: 10000ms

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*.xml

# Feign配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000  # 连接超时时间（毫秒）
        readTimeout: 60000     # 读取超时时间（毫秒）
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

# 日志配置
logging:
  level:
    com.hljy: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
