server:
  port: 8081

spring:
  application:
    name: hljy-user
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${hl.db.host}:3306/db_user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ${hl.db.pw}
  cloud:
    nacos:
      server-addr: 192.168.100.120:8848
      config:
        enabled: false  # 暂时禁用Nacos配置，避免连接问题
# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*.xml

# JWT配置
hljy:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itchaoLoveLink_2025_SecureKey_ABCDEF123456
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    token-name: token


# 日志配置
logging:
  level:
    com.hljy: debug
    org.springframework.security: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
